yolo_model:

  config_file:
    name: yolov3-tiny_turtlebot.cfg
  weight_file:
    name: yolov3-tiny_turtlebot.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - t
      - car
